### ISSUE TITLE
Great

### ISSUE THREAD

**Issue by simplenotezy** [Bobz-zg/WordPress-plugin-boilerplate-with-webpack#1]
This is great, just what I was looking for, I also really enjoy sage. Is this codebase still being maintained? And despite it being 3 years old, are there anything to take into consideration?

A few questions
1) Is blade possible with this build?
2) Are you planning to continue updating the repo?
3) Would you recommend using this repo for a new plugin?

Best regards

**Comment by Bobz-zg** [comment]
Ups. Better late then never, updated plugin is moved to a different repository and will be maintained there: https://github.com/code-soup/wordpress-plugin-boilerplate
